### ISSUE TITLE
The Provided example doesn't work

### ISSUE THREAD

**Issue by Vaimer9** [nickofolas/discord-rich-presence#2]
The example in the readme does not work, even tried using different Application IDs but still get the error
```
Error: "Couldn't connect to the Discord IPC socket"
```

**Comment by nickofolas** [comment]
The example works completely fine on my end. Could you elaborate on your environment at runtime (i.e. system, Discord version, etc)?

**Comment by Vaimer9** [comment]
I am running the program using wsl, using the stable build, I have the discord client on while I am running the program.

**Comment by nickofolas** [comment]
Ah. The issue is that you're trying to run it in WSL. While it's [possible to communicate with Windows named pipes from the Linux subsystem in WSL 1](https://github.com/andweeb/presence.nvim/wiki/Rich-Presence-in-WSL#wsl-1), the same cannot be done in WSL 2.

With the amount of work it requires to get even WSL 1 working in such a manner, your best bet is unfortunately likely to be developing on Windows, or in a full installation of Linux.

**Comment by Vaimer9** [comment]
I tried it on my ubuntu laptop and it still does not work, I still get the same error, maybe this has to do smth with ubuntu as its the only same variable in these 2 situations other than that i don't know what could be the underlying problem

**Comment by Vaimer9** [comment]
Well, shortly after i decided to go full linux and it still does not work getting the same error here, Maybe the prob is ubuntu as its the only same thing between the 2 environments

**Comment by nickofolas** [comment]
If that's the case, and the error is still appearing even when you run the example while Discord is open, then my best guess is that it would have to be an issue beyond the crate itself (i.e. with how you're running it, your system setup, etc).

As for Ubuntu, it has been successfully tested before, so I can't imagine that's the root issue here.
